version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    
  web:
    image: bearfood-api:latest
    container_name: dotnet-mvc
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql
    ports:
      - "5025:5025"
        
volumes:
  mssql-data:
